//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Language.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Ads.
        /// </summary>
        public static string AllItemMarketPageTitle {
            get {
                return ResourceManager.GetString("AllItemMarketPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Free Ad.
        /// </summary>
        public static string ButonTextPostFreeAd {
            get {
                return ResourceManager.GetString("ButonTextPostFreeAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD YOUR PRODUCT.
        /// </summary>
        public static string ButtonTextAddYourProduct {
            get {
                return ResourceManager.GetString("ButtonTextAddYourProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string ButtonTextAdvancedSearch {
            get {
                return ResourceManager.GetString("ButtonTextAdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTINUE SHOPPING.
        /// </summary>
        public static string ButtonTextCartContinueShopping {
            get {
                return ResourceManager.GetString("ButtonTextCartContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW CART.
        /// </summary>
        public static string ButtonTextCartViewCart {
            get {
                return ResourceManager.GetString("ButtonTextCartViewCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonTextClose {
            get {
                return ResourceManager.GetString("ButtonTextClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Ads.
        /// </summary>
        public static string ButtonTextCompanyAd {
            get {
                return ResourceManager.GetString("ButtonTextCompanyAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        public static string ButtonTextContactSUBMIT {
            get {
                return ResourceManager.GetString("ButtonTextContactSUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FA.
        /// </summary>
        public static string ButtonTextFabia {
            get {
                return ResourceManager.GetString("ButtonTextFabia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Rent.
        /// </summary>
        public static string ButtonTextForRent {
            get {
                return ResourceManager.GetString("ButtonTextForRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Sale.
        /// </summary>
        public static string ButtonTextForSale {
            get {
                return ResourceManager.GetString("ButtonTextForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Ads.
        /// </summary>
        public static string ButtonTextIndividualAd {
            get {
                return ResourceManager.GetString("ButtonTextIndividualAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERESTS.
        /// </summary>
        public static string ButtonTextInterest {
            get {
                return ResourceManager.GetString("ButtonTextInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOIN AS PROVIDER.
        /// </summary>
        public static string ButtonTextJoinAsProvider {
            get {
                return ResourceManager.GetString("ButtonTextJoinAsProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARKETS.
        /// </summary>
        public static string ButtonTextMarkets {
            get {
                return ResourceManager.GetString("ButtonTextMarkets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string ButtonTextNewItem {
            get {
                return ResourceManager.GetString("ButtonTextNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Picture.
        /// </summary>
        public static string ButtonTextNewPostAddNewPicture {
            get {
                return ResourceManager.GetString("ButtonTextNewPostAddNewPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string ButtonTextRegisterSignUp {
            get {
                return ResourceManager.GetString("ButtonTextRegisterSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string ButtonTextSignin {
            get {
                return ResourceManager.GetString("ButtonTextSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIAL.
        /// </summary>
        public static string ButtonTextSpecial {
            get {
                return ResourceManager.GetString("ButtonTextSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT AD.
        /// </summary>
        public static string ButtonTextSubmitAd {
            get {
                return ResourceManager.GetString("ButtonTextSubmitAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent Deals.
        /// </summary>
        public static string ButtonTextUrgentSale {
            get {
                return ResourceManager.GetString("ButtonTextUrgentSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Item.
        /// </summary>
        public static string ButtonTextUsedItem {
            get {
                return ResourceManager.GetString("ButtonTextUsedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market .
        /// </summary>
        public static string CategoryMarketPageTitle {
            get {
                return ResourceManager.GetString("CategoryMarketPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUsPageTitle {
            get {
                return ResourceManager.GetString("ContactUsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ErrorMessageContactUsContactEmail {
            get {
                return ResourceManager.GetString("ErrorMessageContactUsContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Message Category.
        /// </summary>
        public static string ErrorMessageContactUsContactMessageCategory {
            get {
                return ResourceManager.GetString("ErrorMessageContactUsContactMessageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ErrorMessageContactUsContactName {
            get {
                return ResourceManager.GetString("ErrorMessageContactUsContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Subject .
        /// </summary>
        public static string ErrorMessageContactUsContactSubject {
            get {
                return ResourceManager.GetString("ErrorMessageContactUsContactSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required. Please enter..
        /// </summary>
        public static string ErrorMessageEmailRequired {
            get {
                return ResourceManager.GetString("ErrorMessageEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is required! Please enter..
        /// </summary>
        public static string ErrorMessageNewPostCategory {
            get {
                return ResourceManager.GetString("ErrorMessageNewPostCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required! Please enter..
        /// </summary>
        public static string ErrorMessageNewPostEmail {
            get {
                return ResourceManager.GetString("ErrorMessageNewPostEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name is required! Please enter..
        /// </summary>
        public static string ErrorMessageNewPostFullName {
            get {
                return ResourceManager.GetString("ErrorMessageNewPostFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is required! Please enter..
        /// </summary>
        public static string ErrorMessageNewPostLocation {
            get {
                return ResourceManager.GetString("ErrorMessageNewPostLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required! Please enter..
        /// </summary>
        public static string ErrorMessageNewPostPassword {
            get {
                return ResourceManager.GetString("ErrorMessageNewPostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is required! Please enter..
        /// </summary>
        public static string ErrorMessageNewPostPhoneNumber {
            get {
                return ResourceManager.GetString("ErrorMessageNewPostPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is required! Please enter..
        /// </summary>
        public static string ErrorMessageNewPostPrice {
            get {
                return ResourceManager.GetString("ErrorMessageNewPostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Password is required! Please enter..
        /// </summary>
        public static string ErrorMessageNewPostRePassword {
            get {
                return ResourceManager.GetString("ErrorMessageNewPostRePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category is required! Please enter..
        /// </summary>
        public static string ErrorMessageNewPostSubCategory {
            get {
                return ResourceManager.GetString("ErrorMessageNewPostSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required! Please enter..
        /// </summary>
        public static string ErrorMessageNewPostTitle {
            get {
                return ResourceManager.GetString("ErrorMessageNewPostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required. Please enter..
        /// </summary>
        public static string ErrorMessagePasswordRequired {
            get {
                return ResourceManager.GetString("ErrorMessagePasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required. Please enter..
        /// </summary>
        public static string ErrorMessageRegisterEmailRequired {
            get {
                return ResourceManager.GetString("ErrorMessageRegisterEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required. Please enter..
        /// </summary>
        public static string ErrorMessageRegisterPasswordRequired {
            get {
                return ResourceManager.GetString("ErrorMessageRegisterPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person/Company name is required. Please enter..
        /// </summary>
        public static string ErrorMessageRegisterPersonRequired {
            get {
                return ResourceManager.GetString("ErrorMessageRegisterPersonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is required. Please enter..
        /// </summary>
        public static string ErrorMessageRegisterPhoneRequired {
            get {
                return ResourceManager.GetString("ErrorMessageRegisterPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Password is required. Please enter..
        /// </summary>
        public static string ErrorMessageRegisterRePasswordRequired {
            get {
                return ResourceManager.GetString("ErrorMessageRegisterRePasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQPageTitle {
            get {
                return ResourceManager.GetString("FAQPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home | .
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Details.
        /// </summary>
        public static string ItemDetailsPageTitle {
            get {
                return ResourceManager.GetString("ItemDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string LabelAdvancedSearch {
            get {
                return ResourceManager.GetString("LabelAdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVERTISE DETAILS.
        /// </summary>
        public static string LabelAdvertiseDetails {
            get {
                return ResourceManager.GetString("LabelAdvertiseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL MARKETS.
        /// </summary>
        public static string LabelAllMarkets {
            get {
                return ResourceManager.GetString("LabelAllMarkets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string LabelContactUs {
            get {
                return ResourceManager.GetString("LabelContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LabelContactUsContactEmail {
            get {
                return ResourceManager.GetString("LabelContactUsContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Form.
        /// </summary>
        public static string LabelContactUsContactForm {
            get {
                return ResourceManager.GetString("LabelContactUsContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message .
        /// </summary>
        public static string LabelContactUsContactMessage {
            get {
                return ResourceManager.GetString("LabelContactUsContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Category.
        /// </summary>
        public static string LabelContactUsContactMessageCategory {
            get {
                return ResourceManager.GetString("LabelContactUsContactMessageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LabelContactUsContactName {
            get {
                return ResourceManager.GetString("LabelContactUsContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject .
        /// </summary>
        public static string LabelContactUsContactSubject {
            get {
                return ResourceManager.GetString("LabelContactUsContactSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEALS  END TODAY!.
        /// </summary>
        public static string LabelDealsEndToday {
            get {
                return ResourceManager.GetString("LabelDealsEndToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have account? Please.
        /// </summary>
        public static string LabelDonotHaveAccount {
            get {
                return ResourceManager.GetString("LabelDonotHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE ENTER CREDENTIALS:.
        /// </summary>
        public static string LabelEnterCredentials {
            get {
                return ResourceManager.GetString("LabelEnterCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FABIA SERVICE.
        /// </summary>
        public static string LabelFabiaService {
            get {
                return ResourceManager.GetString("LabelFabiaService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEATURED!.
        /// </summary>
        public static string LabelFeatured {
            get {
                return ResourceManager.GetString("LabelFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOR GIFT!.
        /// </summary>
        public static string LabelForGift {
            get {
                return ResourceManager.GetString("LabelForGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi!.
        /// </summary>
        public static string LabelHi {
            get {
                return ResourceManager.GetString("LabelHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEN &amp; WOMEN.
        /// </summary>
        public static string LabelMenAndWomen {
            get {
                return ResourceManager.GetString("LabelMenAndWomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertiser Details.
        /// </summary>
        public static string LabelNewPostAdvertiserDetails {
            get {
                return ResourceManager.GetString("LabelNewPostAdvertiserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string LabelNewPostArea {
            get {
                return ResourceManager.GetString("LabelNewPostArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand new.
        /// </summary>
        public static string LabelNewPostBrandNew {
            get {
                return ResourceManager.GetString("LabelNewPostBrandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category *.
        /// </summary>
        public static string LabelNewPostCategory {
            get {
                return ResourceManager.GetString("LabelNewPostCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string LabelNewPostCompany {
            get {
                return ResourceManager.GetString("LabelNewPostCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string LabelNewPostCondition {
            get {
                return ResourceManager.GetString("LabelNewPostCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description.
        /// </summary>
        public static string LabelNewPostDescription {
            get {
                return ResourceManager.GetString("LabelNewPostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LabelNewPostEmail {
            get {
                return ResourceManager.GetString("LabelNewPostEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string LabelNewPostFullName {
            get {
                return ResourceManager.GetString("LabelNewPostFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am:.
        /// </summary>
        public static string LabelNewPostIAm {
            get {
                return ResourceManager.GetString("LabelNewPostIAm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string LabelNewPostIndividual {
            get {
                return ResourceManager.GetString("LabelNewPostIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LabelNewPostLocation {
            get {
                return ResourceManager.GetString("LabelNewPostLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Urgent Deal.
        /// </summary>
        public static string LabelNewPostNotUrgentDeal {
            get {
                return ResourceManager.GetString("LabelNewPostNotUrgentDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LabelNewPostPassword {
            get {
                return ResourceManager.GetString("LabelNewPostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string LabelNewPostPhoneNumber {
            get {
                return ResourceManager.GetString("LabelNewPostPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (BDT)*.
        /// </summary>
        public static string LabelNewPostPrice {
            get {
                return ResourceManager.GetString("LabelNewPostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Password.
        /// </summary>
        public static string LabelNewPostRePassword {
            get {
                return ResourceManager.GetString("LabelNewPostRePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Tag.
        /// </summary>
        public static string LabelNewPostSearchTag {
            get {
                return ResourceManager.GetString("LabelNewPostSearchTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string LabelNewPostSignIN {
            get {
                return ResourceManager.GetString("LabelNewPostSignIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category *.
        /// </summary>
        public static string LabelNewPostSubCategory {
            get {
                return ResourceManager.GetString("LabelNewPostSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Title *.
        /// </summary>
        public static string LabelNewPostTitle {
            get {
                return ResourceManager.GetString("LabelNewPostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD PICTURE.
        /// </summary>
        public static string LabelNewPostUploadPicture {
            get {
                return ResourceManager.GetString("LabelNewPostUploadPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent Deal.
        /// </summary>
        public static string LabelNewPostUrgentDeal {
            get {
                return ResourceManager.GetString("LabelNewPostUrgentDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Item.
        /// </summary>
        public static string LabelNewPostUsedItem {
            get {
                return ResourceManager.GetString("LabelNewPostUsedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POPULAR CATEGORIES.
        /// </summary>
        public static string LabelPopularCategory {
            get {
                return ResourceManager.GetString("LabelPopularCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POPULAR PRODUCTS.
        /// </summary>
        public static string LabelPopularProduct {
            get {
                return ResourceManager.GetString("LabelPopularProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Fee Ad.
        /// </summary>
        public static string LabelPostFreeAd {
            get {
                return ResourceManager.GetString("LabelPostFreeAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREMIUM PRODUCTS.
        /// </summary>
        public static string LabelPremiumProducts {
            get {
                return ResourceManager.GetString("LabelPremiumProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Your Account:.
        /// </summary>
        public static string LabelRegisterYourAccount {
            get {
                return ResourceManager.GetString("LabelRegisterYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKILLS &amp; SERVICES.
        /// </summary>
        public static string LabelSkillsAndServices {
            get {
                return ResourceManager.GetString("LabelSkillsAndServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPONSORED.
        /// </summary>
        public static string LabelSponsor {
            get {
                return ResourceManager.GetString("LabelSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOR STUDENTS!.
        /// </summary>
        public static string LabelStudents {
            get {
                return ResourceManager.GetString("LabelStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODAY’S PICKUPS.
        /// </summary>
        public static string LabelTodayPickups {
            get {
                return ResourceManager.GetString("LabelTodayPickups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View By Markets.
        /// </summary>
        public static string LabelViewByMarkets {
            get {
                return ResourceManager.GetString("LabelViewByMarkets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WE PROMOTE!.
        /// </summary>
        public static string LabelWeSponsored {
            get {
                return ResourceManager.GetString("LabelWeSponsored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Admin Content.
        /// </summary>
        public static string LinkAddShortContent {
            get {
                return ResourceManager.GetString("LinkAddShortContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD TO CART.
        /// </summary>
        public static string LinkAddToCart {
            get {
                return ResourceManager.GetString("LinkAddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads.
        /// </summary>
        public static string LinkAds {
            get {
                return ResourceManager.GetString("LinkAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bn.
        /// </summary>
        public static string LinkBangla {
            get {
                return ResourceManager.GetString("LinkBangla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Reports.
        /// </summary>
        public static string LinkBusinessIntelligence {
            get {
                return ResourceManager.GetString("LinkBusinessIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string LinkCart {
            get {
                return ResourceManager.GetString("LinkCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Package.
        /// </summary>
        public static string LinkConfigurePackage {
            get {
                return ResourceManager.GetString("LinkConfigurePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Content.
        /// </summary>
        public static string LinkConfigurePanels {
            get {
                return ResourceManager.GetString("LinkConfigurePanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Package Prices.
        /// </summary>
        public static string LinkConfigurePrice {
            get {
                return ResourceManager.GetString("LinkConfigurePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string LinkContact {
            get {
                return ResourceManager.GetString("LinkContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshi Hut Bazar.
        /// </summary>
        public static string LinkDeshiHutBazar {
            get {
                return ResourceManager.GetString("LinkDeshiHutBazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string LinkDonate {
            get {
                return ResourceManager.GetString("LinkDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Pictures.
        /// </summary>
        public static string LinkEditImages {
            get {
                return ResourceManager.GetString("LinkEditImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eng.
        /// </summary>
        public static string LinkEnglish {
            get {
                return ResourceManager.GetString("LinkEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabia Services.
        /// </summary>
        public static string LinkFabiaServices {
            get {
                return ResourceManager.GetString("LinkFabiaServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string LinkFaq {
            get {
                return ResourceManager.GetString("LinkFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password?.
        /// </summary>
        public static string LinkForgetPassword {
            get {
                return ResourceManager.GetString("LinkForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Ads.
        /// </summary>
        public static string LinkLatestAds {
            get {
                return ResourceManager.GetString("LinkLatestAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LinkLogout {
            get {
                return ResourceManager.GetString("LinkLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Log Reports.
        /// </summary>
        public static string LinkLogReports {
            get {
                return ResourceManager.GetString("LinkLogReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account.
        /// </summary>
        public static string LinkManageAccount {
            get {
                return ResourceManager.GetString("LinkManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Admin Contents.
        /// </summary>
        public static string LinkManageAdminContents {
            get {
                return ResourceManager.GetString("LinkManageAdminContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Bills.
        /// </summary>
        public static string LinkManageBikashBills {
            get {
                return ResourceManager.GetString("LinkManageBikashBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Company Account.
        /// </summary>
        public static string LinkManageCompanyAccount {
            get {
                return ResourceManager.GetString("LinkManageCompanyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabia Providers.
        /// </summary>
        public static string LinkMyFabiaServiceProviders {
            get {
                return ResourceManager.GetString("LinkMyFabiaServiceProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ng.
        /// </summary>
        public static string LinkNigeria {
            get {
                return ResourceManager.GetString("LinkNigeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Status.
        /// </summary>
        public static string LinkOurStatus {
            get {
                return ResourceManager.GetString("LinkOurStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshi Hut Bazar.
        /// </summary>
        public static string LinkPortalURL {
            get {
                return ResourceManager.GetString("LinkPortalURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string LinkPrivacyAndTerms {
            get {
                return ResourceManager.GetString("LinkPrivacyAndTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Ads.
        /// </summary>
        public static string LinkPublishedPosts {
            get {
                return ResourceManager.GetString("LinkPublishedPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up.
        /// </summary>
        public static string LinkRegister {
            get {
                return ResourceManager.GetString("LinkRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string LinkResources {
            get {
                return ResourceManager.GetString("LinkResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid Ads.
        /// </summary>
        public static string LinkUnpaidPosts {
            get {
                return ResourceManager.GetString("LinkUnpaidPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW MORE.
        /// </summary>
        public static string LinkViewMore {
            get {
                return ResourceManager.GetString("LinkViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping cart updated! Do you want to continue shopping or view cart?.
        /// </summary>
        public static string MessageTextCartContinueMessage {
            get {
                return ResourceManager.GetString("MessageTextCartContinueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you very much..
        /// </summary>
        public static string NoteContactUsThankyouVeryMuch {
            get {
                return ResourceManager.GetString("NoteContactUsThankyouVeryMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: It is very simple. For quick submission, please fill up only the * fields..
        /// </summary>
        public static string NotePostFreeAd {
            get {
                return ResourceManager.GetString("NotePostFreeAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please leave us your message to improve our website better. We will highly appreciate your feedback and we will respond to you at the earliest because your satisfaction is our achievement..
        /// </summary>
        public static string NotetContactUsIntroGreetingMessageText {
            get {
                return ResourceManager.GetString("NotetContactUsIntroGreetingMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PlaceholderContactUsContactEmail {
            get {
                return ResourceManager.GetString("PlaceholderContactUsContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Message Category.
        /// </summary>
        public static string PlaceholderContactUsContactMessageCategory {
            get {
                return ResourceManager.GetString("PlaceholderContactUsContactMessageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PlaceholderContactUsContactName {
            get {
                return ResourceManager.GetString("PlaceholderContactUsContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Subject .
        /// </summary>
        public static string PlaceholderContactUsContactSubject {
            get {
                return ResourceManager.GetString("PlaceholderContactUsContactSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PlaceholderEmail {
            get {
                return ResourceManager.GetString("PlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Details.
        /// </summary>
        public static string PlaceholderNewPostArea {
            get {
                return ResourceManager.GetString("PlaceholderNewPostArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category .
        /// </summary>
        public static string PlaceholderNewPostCategory {
            get {
                return ResourceManager.GetString("PlaceholderNewPostCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description.
        /// </summary>
        public static string PlaceholderNewPostDescription {
            get {
                return ResourceManager.GetString("PlaceholderNewPostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PlaceholderNewPostEmail {
            get {
                return ResourceManager.GetString("PlaceholderNewPostEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string PlaceholderNewPostFullName {
            get {
                return ResourceManager.GetString("PlaceholderNewPostFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State.
        /// </summary>
        public static string PlaceholderNewPostLocation {
            get {
                return ResourceManager.GetString("PlaceholderNewPostLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PlaceholderNewPostPassword {
            get {
                return ResourceManager.GetString("PlaceholderNewPostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PlaceholderNewPostPhoneNumber {
            get {
                return ResourceManager.GetString("PlaceholderNewPostPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (BDT).
        /// </summary>
        public static string PlaceholderNewPostPrice {
            get {
                return ResourceManager.GetString("PlaceholderNewPostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Password.
        /// </summary>
        public static string PlaceholderNewPostRePassword {
            get {
                return ResourceManager.GetString("PlaceholderNewPostRePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Tag.
        /// </summary>
        public static string PlaceholderNewPostSearchTag {
            get {
                return ResourceManager.GetString("PlaceholderNewPostSearchTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sub Category.
        /// </summary>
        public static string PlaceholderNewPostSubCategory {
            get {
                return ResourceManager.GetString("PlaceholderNewPostSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Title.
        /// </summary>
        public static string PlaceholderNewPostTitle {
            get {
                return ResourceManager.GetString("PlaceholderNewPostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PlaceholderPassword {
            get {
                return ResourceManager.GetString("PlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person / Company Name.
        /// </summary>
        public static string PlaceholderPersonCompany {
            get {
                return ResourceManager.GetString("PlaceholderPersonCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (Ends With).
        /// </summary>
        public static string PlaceholderPriceEndsWith {
            get {
                return ResourceManager.GetString("PlaceholderPriceEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (Starts From).
        /// </summary>
        public static string PlaceholderPriceStartsFrom {
            get {
                return ResourceManager.GetString("PlaceholderPriceStartsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PlaceholderRegisterEmail {
            get {
                return ResourceManager.GetString("PlaceholderRegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PlaceholderRegisterPassword {
            get {
                return ResourceManager.GetString("PlaceholderRegisterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PlaceholderRegisterPhone {
            get {
                return ResourceManager.GetString("PlaceholderRegisterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Password.
        /// </summary>
        public static string PlaceholderRegisterRePassword {
            get {
                return ResourceManager.GetString("PlaceholderRegisterRePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string PlaceholderSelectCategory {
            get {
                return ResourceManager.GetString("PlaceholderSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State.
        /// </summary>
        public static string PlaceholderSelectState {
            get {
                return ResourceManager.GetString("PlaceholderSelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sub-Category.
        /// </summary>
        public static string PlaceholderSelectSubCategory {
            get {
                return ResourceManager.GetString("PlaceholderSelectSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to search ….
        /// </summary>
        public static string PlaceHolderSimpleSearchTextBox {
            get {
                return ResourceManager.GetString("PlaceHolderSimpleSearchTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific area details ….
        /// </summary>
        public static string PlaceholderSpecificAreaDetails {
            get {
                return ResourceManager.GetString("PlaceholderSpecificAreaDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string PrivacyPageTitle {
            get {
                return ResourceManager.GetString("PrivacyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string SigninPageTitle {
            get {
                return ResourceManager.GetString("SigninPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string SignupPageTitle {
            get {
                return ResourceManager.GetString("SignupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Market.
        /// </summary>
        public static string SpecialMarketPageTitle {
            get {
                return ResourceManager.GetString("SpecialMarketPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Market.
        /// </summary>
        public static string SubCategoryMarketPageTitle {
            get {
                return ResourceManager.GetString("SubCategoryMarketPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual / Private Advertiser Account: Individual Advertiser users post ads to sell products or services. They can only publish ads in this online portal to find buyers. Visitors view ads and call directly to the advertiser to buy products or avail services.
        /// </summary>
        public static string TextIndividualUserDescription {
            get {
                return ResourceManager.GetString("TextIndividualUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business / Online Seller Account: Business users post their product or service details in this portal and online visitors buy those products using online payment gateway. A business user represents a company which must be registered to operate business in Bangladesh..
        /// </summary>
        public static string TextOnlineSellerUserDescription {
            get {
                return ResourceManager.GetString("TextOnlineSellerUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied!.
        /// </summary>
        public static string UnwantedAccessErrorPageTitle {
            get {
                return ResourceManager.GetString("UnwantedAccessErrorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact us.
        /// </summary>
        public static string UnwantedAcessErrorAContactUs {
            get {
                return ResourceManager.GetString("UnwantedAcessErrorAContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support team.
        /// </summary>
        public static string UnwantedAcessErrorDivSupportTeam {
            get {
                return ResourceManager.GetString("UnwantedAcessErrorDivSupportTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Try, System cannot serve this page..
        /// </summary>
        public static string UnwantedAcessErrorH3ErrorTitle {
            get {
                return ResourceManager.GetString("UnwantedAcessErrorH3ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized User.
        /// </summary>
        public static string UnwantedAcessErrorH4Reason1 {
            get {
                return ResourceManager.GetString("UnwantedAcessErrorH4Reason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Terminated.
        /// </summary>
        public static string UnwantedAcessErrorH4Reason2 {
            get {
                return ResourceManager.GetString("UnwantedAcessErrorH4Reason2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons could be:.
        /// </summary>
        public static string UnwantedAcessErrorH4ReasonsCouldBe {
            get {
                return ResourceManager.GetString("UnwantedAcessErrorH4ReasonsCouldBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform Admin about this failure.
        /// </summary>
        public static string UnwantedAcessErrorH4Solution {
            get {
                return ResourceManager.GetString("UnwantedAcessErrorH4Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go to.
        /// </summary>
        public static string UnwantedAcessErrorPPleaseGoTo {
            get {
                return ResourceManager.GetString("UnwantedAcessErrorPPleaseGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user who requested this page has no permission to see this page or may be the user is not a valid user in www.seeasy.com..
        /// </summary>
        public static string UnwantedAcessErrorPReason1Text {
            get {
                return ResourceManager.GetString("UnwantedAcessErrorPReason1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user session might be terminated, causing the user access not valid for this time. Please sign in again to access this page..
        /// </summary>
        public static string UnwantedAcessErrorPReason2Text {
            get {
                return ResourceManager.GetString("UnwantedAcessErrorPReason2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to report about this failure..
        /// </summary>
        public static string UnwantedAcessErrorPToReportFailure {
            get {
                return ResourceManager.GetString("UnwantedAcessErrorPToReportFailure", resourceCulture);
            }
        }
    }
}
