//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageCategoryList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageCategoryList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Language.LanguageCategoryList", typeof(LanguageCategoryList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio &amp; Sound Systems.
        /// </summary>
        internal static string AudioAndSoundSystems {
            get {
                return ResourceManager.GetString("AudioAndSoundSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diapers.
        /// </summary>
        internal static string BabyDiapers {
            get {
                return ResourceManager.GetString("BabyDiapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Gears &amp; Nursery.
        /// </summary>
        internal static string BabyGears {
            get {
                return ResourceManager.GetString("BabyGears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Clothing &amp; Maternity.
        /// </summary>
        internal static string BabyMaternity {
            get {
                return ResourceManager.GetString("BabyMaternity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bath, Bed &amp; Decor.
        /// </summary>
        internal static string BathBedAndDecor {
            get {
                return ResourceManager.GetString("BathBedAndDecor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty.
        /// </summary>
        internal static string Beauty {
            get {
                return ResourceManager.GetString("Beauty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty Supplements.
        /// </summary>
        internal static string BeautySupplements {
            get {
                return ResourceManager.GetString("BeautySupplements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty Tools.
        /// </summary>
        internal static string BeautyTools {
            get {
                return ResourceManager.GetString("BeautyTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beverages.
        /// </summary>
        internal static string Beverages {
            get {
                return ResourceManager.GetString("Beverages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera &amp; Accessories.
        /// </summary>
        internal static string CameraAndAccessories {
            get {
                return ResourceManager.GetString("CameraAndAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Essentials.
        /// </summary>
        internal static string CarEssentials {
            get {
                return ResourceManager.GetString("CarEssentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Oils &amp; Fluids.
        /// </summary>
        internal static string CarOilFluids {
            get {
                return ResourceManager.GetString("CarOilFluids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services &amp; Installations.
        /// </summary>
        internal static string CarServicesInstallations {
            get {
                return ResourceManager.GetString("CarServicesInstallations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooling &amp; Heating.
        /// </summary>
        internal static string CoolingAndHeating {
            get {
                return ResourceManager.GetString("CoolingAndHeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die And Cleaning.
        /// </summary>
        internal static string DiyAndCleaning {
            get {
                return ResourceManager.GetString("DiyAndCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        internal static string Electronics {
            get {
                return ResourceManager.GetString("Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export &amp; Import.
        /// </summary>
        internal static string ExportImport {
            get {
                return ResourceManager.GetString("ExportImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Products.
        /// </summary>
        internal static string ExportProducts {
            get {
                return ResourceManager.GetString("ExportProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness &amp; Lifestyles.
        /// </summary>
        internal static string FitnessAndLifeStyles {
            get {
                return ResourceManager.GetString("FitnessAndLifeStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness &amp; Sports Equipments.
        /// </summary>
        internal static string FitnessEquipments {
            get {
                return ResourceManager.GetString("FitnessEquipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture.
        /// </summary>
        internal static string Furniture {
            get {
                return ResourceManager.GetString("Furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Fitness.
        /// </summary>
        internal static string GlobalFittness {
            get {
                return ResourceManager.GetString("GlobalFittness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groceries &amp; Pets.
        /// </summary>
        internal static string Groceries {
            get {
                return ResourceManager.GetString("Groceries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grocery Essentials.
        /// </summary>
        internal static string GroceryEssentials {
            get {
                return ResourceManager.GetString("GroceryEssentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair, Bath &amp; Body.
        /// </summary>
        internal static string HairBathBody {
            get {
                return ResourceManager.GetString("HairBathBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire.
        /// </summary>
        internal static string HireMe {
            get {
                return ResourceManager.GetString("HireMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office and Living.
        /// </summary>
        internal static string HomeAndLivings {
            get {
                return ResourceManager.GetString("HomeAndLivings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Products.
        /// </summary>
        internal static string ImportProducts {
            get {
                return ResourceManager.GetString("ImportProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen &amp; Dining.
        /// </summary>
        internal static string KitchenAndDining {
            get {
                return ResourceManager.GetString("KitchenAndDining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen Appliances.
        /// </summary>
        internal static string KitchenAppliances {
            get {
                return ResourceManager.GetString("KitchenAppliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laptop &amp; Computer.
        /// </summary>
        internal static string LaptopAndComputer {
            get {
                return ResourceManager.GetString("LaptopAndComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Appliances.
        /// </summary>
        internal static string LargeAppliances {
            get {
                return ResourceManager.GetString("LargeAppliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laundry.
        /// </summary>
        internal static string Laundry {
            get {
                return ResourceManager.GetString("Laundry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makeup.
        /// </summary>
        internal static string Makeup {
            get {
                return ResourceManager.GetString("Makeup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Supplies.
        /// </summary>
        internal static string MedicalSupplies {
            get {
                return ResourceManager.GetString("MedicalSupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dresses.
        /// </summary>
        internal static string MenDresses {
            get {
                return ResourceManager.GetString("MenDresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men Fashion.
        /// </summary>
        internal static string MenFashion {
            get {
                return ResourceManager.GetString("MenFashion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        internal static string MenFashionAccessories {
            get {
                return ResourceManager.GetString("MenFashionAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        internal static string MenShoes {
            get {
                return ResourceManager.GetString("MenShoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        internal static string MenShoes1 {
            get {
                return ResourceManager.GetString("MenShoes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men Sportswear.
        /// </summary>
        internal static string MensSportswear {
            get {
                return ResourceManager.GetString("MensSportswear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet &amp; Bags.
        /// </summary>
        internal static string MenWaletBags {
            get {
                return ResourceManager.GetString("MenWaletBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watches.
        /// </summary>
        internal static string MenWatches {
            get {
                return ResourceManager.GetString("MenWatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phones.
        /// </summary>
        internal static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor.
        /// </summary>
        internal static string Motor {
            get {
                return ResourceManager.GetString("Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Cycle Essentials.
        /// </summary>
        internal static string MotorCycleEssentials {
            get {
                return ResourceManager.GetString("MotorCycleEssentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music, Books &amp; Games.
        /// </summary>
        internal static string MusicBooksGames {
            get {
                return ResourceManager.GetString("MusicBooksGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuts.
        /// </summary>
        internal static string Nuts {
            get {
                return ResourceManager.GetString("Nuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Furniture.
        /// </summary>
        internal static string OfficeFurniture {
            get {
                return ResourceManager.GetString("OfficeFurniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string OtherProductItems {
            get {
                return ResourceManager.GetString("OtherProductItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string OtherServiceItems {
            get {
                return ResourceManager.GetString("OtherServiceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Care.
        /// </summary>
        internal static string PersonalCare {
            get {
                return ResourceManager.GetString("PersonalCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets.
        /// </summary>
        internal static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy.
        /// </summary>
        internal static string Pharmacy {
            get {
                return ResourceManager.GetString("Pharmacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Accessories.
        /// </summary>
        internal static string PhoneAccessorie {
            get {
                return ResourceManager.GetString("PhoneAccessorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin Care.
        /// </summary>
        internal static string SkinCare {
            get {
                return ResourceManager.GetString("SkinCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snacks &amp; Cookies.
        /// </summary>
        internal static string SnacksCookies {
            get {
                return ResourceManager.GetString("SnacksCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectacles.
        /// </summary>
        internal static string Specticals {
            get {
                return ResourceManager.GetString("Specticals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectacles.
        /// </summary>
        internal static string Specticals1 {
            get {
                return ResourceManager.GetString("Specticals1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablet &amp; Gadgets.
        /// </summary>
        internal static string TabletAndGadget {
            get {
                return ResourceManager.GetString("TabletAndGadget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toys &amp; Games.
        /// </summary>
        internal static string ToysGames {
            get {
                return ResourceManager.GetString("ToysGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toys, Kids &amp; Babies.
        /// </summary>
        internal static string ToysKidsAndBabies {
            get {
                return ResourceManager.GetString("ToysKidsAndBabies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training, Hire &amp; Travels.
        /// </summary>
        internal static string TrainingHireTravels {
            get {
                return ResourceManager.GetString("TrainingHireTravels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Packages.
        /// </summary>
        internal static string TrainingPackages {
            get {
                return ResourceManager.GetString("TrainingPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Packages.
        /// </summary>
        internal static string TravelPackages {
            get {
                return ResourceManager.GetString("TravelPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV &amp; Home Audio.
        /// </summary>
        internal static string TVAndHomeAudio {
            get {
                return ResourceManager.GetString("TVAndHomeAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV &amp; Home Appliances.
        /// </summary>
        internal static string TVHomeAppliances {
            get {
                return ResourceManager.GetString("TVHomeAppliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuum &amp; Floor Care.
        /// </summary>
        internal static string VacuumAndFloorCare {
            get {
                return ResourceManager.GetString("VacuumAndFloorCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellbeing.
        /// </summary>
        internal static string Wellbeings {
            get {
                return ResourceManager.GetString("Wellbeings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman Fashion.
        /// </summary>
        internal static string WomanFashion {
            get {
                return ResourceManager.GetString("WomanFashion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bags.
        /// </summary>
        internal static string WomenBags {
            get {
                return ResourceManager.GetString("WomenBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dresses.
        /// </summary>
        internal static string WomenDresses {
            get {
                return ResourceManager.GetString("WomenDresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion Accessories.
        /// </summary>
        internal static string WomenFashionAccessories {
            get {
                return ResourceManager.GetString("WomenFashionAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boishak Dress.
        /// </summary>
        internal static string WomenFashionWomenBoishakDress {
            get {
                return ResourceManager.GetString("WomenFashionWomenBoishakDress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewelries.
        /// </summary>
        internal static string WomenGolds {
            get {
                return ResourceManager.GetString("WomenGolds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sportswear.
        /// </summary>
        internal static string WomensSportswear {
            get {
                return ResourceManager.GetString("WomensSportswear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watches.
        /// </summary>
        internal static string WomenWatches {
            get {
                return ResourceManager.GetString("WomenWatches", resourceCulture);
            }
        }
    }
}
