// <auto-generated />
namespace Model
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class new_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_db));
        
        string IMigrationMetadata.Id
        {
            get { return "202005301103363_new_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
